name: arduinomqtt
version: 0.1
summary: Reads the data from Arduino and sends to MQTT sensor/arduino/in
description: This snap connects to a local mqtt broker that listens on port 1883 and publishes everything it can read from the usb interface and is sent by Arduiono.
confinement: devmode  # use "strict" to enforce system access only via declared interfaces
grade: stable # use "stable" to assert the snap quality

apps:
    arduino:
        command: bin/usbserial
        daemon: simple
        plugs:
          - network
          - network-control
          - serial

parts:
   arduino:
     plugin: go
     source: src/github.com/mectors/usbserial
